SELECT GRADE,COUNT(DISTINCT CUSTOMERID)
FROM CUSTOMER
GROUP BY GRADE
HAVING GRADE>(SELECT AVG(GRADE)
FROM CUSTOMER
WHERE CITY='BANGALORE');

SELECT SALESMANID, NAME
FROM SALESMAN A
WHERE 1<(SELECT COUNT(*)
FROM CUSTOMER
WHERE SALESMANID=A.SALESMANID);

SELECT SALESMAN.SALESMANID, NAME,CUSTNAME,COMMISSION
FROM SALESMAN,CUSTOMER
WHERE SALESMAN.CITY=CUSTOMER.CITY
UNION
SELECT SALESMANID,NAME,'NO MATCH',COMMISSION
FROM SALESMAN
WHERE NOT CITY=ANY
(SELECT CITY
FROM CUSTOMER)
ORDER BY 2 DESC;

CREATE VIEW ELITSALESMAN AS
SELECT B.ORDDATE,A.SALESMANID,A.NAME
FROM SALESMAN A,ORDERS B
WHEREA.SALESMANID=B.SALESMANID
AND B.PURCHASEAMT=(SELECT MAX(PURCHASEAMT)
FROM ORDERS C
WHERE C.ORDDATE=B.ORDDATE);

SELECT * FROM ELITSALESMAN;

DELETE FROM SALESMAN
WHERE SALESMANID=1000;

SELECT * FROM SALESMAN;
